name: pi
version: 18-classic
summary: Raspberry Pi gadget
description: |
 Support files for booting Raspberry Pi.
 This gadget snap supports the Raspberry Pi 2B, 3B, 3A+, 3B+, 4B, Compute
 Module 3, and the Compute Module 3+ universally.
type: gadget
architectures:
  - armhf
  - arm64
  - build-on: amd64
    run-on: armhf
confinement: strict
grade: stable
parts:
  gadget:
    plugin: nil
    override-build: |
      if [ "$(arch)" != "aarch64" -a "$(arch)" != "arm7l" ]; then
        echo "Cross compilation detected; using pre-defined sources list"
        OPTIONAL_ARGS="SOURCES_HOST=\"./helpers/sources.list.cross\""
      fi
      make -C ${SNAPCRAFT_PROJECT_DIR:-.} classic \
        DESTDIR=${SNAPCRAFT_PART_INSTALL} \
        ARCH=$(dpkg-architecture -t "${SNAPCRAFT_ARCH_TRIPLET}" -q DEB_HOST_ARCH) \
        ${OPTIONAL_ARGS:-}
    prime:
      - boot-assets/*
    build-packages:
      - u-boot-tools
      - lsb-release
